version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: weekly
    - package-ecosystem: npm
      commit-message:
          prefix: dependencies
      versioning-strategy: increase
      directory: /
      schedule:
          interval: weekly
      open-pull-requests-limit: 20
      groups:
          typescript-eslint:
              applies-to: version-updates
              patterns:
                  - '@typescript-eslint/*'
          eslint:
              applies-to: version-updates
              patterns:
                  - 'eslint'
                  - '@eslint/js'
          playwright:
              applies-to: version-updates
              patterns:
                  - '*playwright/*'
          axa-oidc:
              applies-to: version-updates
              patterns:
                  - '@axa-fr/*'
    - package-ecosystem: docker
      directory: /docker
      schedule:
          interval: daily
